//
//  Request+YAML.swift
//  SourceKittenFramework
//
//  Created by Zheng Li on 25/11/2017.
//  Copyright © 2017 SourceKitten. All rights reserved.
//

import Foundation

extension Request {
    /// A request generated by sourcekit using the yaml representation.
    public struct YAML: RequestType {
        public let yaml: String

        public func sourcekitObject() -> sourcekitd_object_t {
            return sourcekitd_request_create_from_yaml(yaml, nil)!
        }
    }

    public static func yamlRequest(yaml: String) -> Request {
        return Request(type: YAML(yaml: yaml))
    }
}
