#!/bin/bash

SWIFT_SNAPSHOT=$1

cp -r /Library/Developer/Toolchains/$SWIFT_SNAPSHOT.xctoolchain/usr/local/include/clang-c /usr/local/include/clang-c
curl https://raw.githubusercontent.com/jpsim/SourceKitten/master/script/module.modulemap -o /usr/local/include/clang-c/module.modulemap
ln -s /Library/Developer/Toolchains/$SWIFT_SNAPSHOT.xctoolchain/usr/lib/libclang.dylib /usr/local/lib/libclang.dylib
mkdir -p /usr/local/include/sourcekitdInProc
ln -s /Library/Developer/Toolchains/$SWIFT_SNAPSHOT.xctoolchain/usr/lib/sourcekitd.framework/Headers/sourcekitd.h /usr/local/include/sourcekitdInProc/sourcekitd.h
curl https://static.realm.io/libsourcekitdInProc/$SWIFT_SNAPSHOT/libsourcekitdInProc.dylib -o /usr/local/lib/libsourcekitdInProc.dylib
