name: pod lib lint

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: bundle install --path vendor/bundle
      - run: bundle exec pod repo update
      - run: bundle exec pod lib lint --verbose
