name: SwiftPM

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  Xcode:
    strategy:
      matrix:
        xcode_version: ['15.3', '15.4', '16.0', '16.1']
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode_version }}
      - run: xcodebuild -version
      - run: swift -version
      - run: swift test

  Linux:
    strategy:
      matrix:
        tag: ['5.8', '5.9', '5.10', '6.0']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v3
      - run: swift test --parallel
